### PR TITLE
Added /u/sodypop's css fix

### PR DESCRIPTION
**Pull request by aperson**
^

### CODE REVIEW

**Comment by dakira** [comment]
@Daniel-McGuire can you test this and merge? If I read this correctly it's to fix the styles when NOT using an adblocker to correctly display Reddit promotions.

**Comment by aperson** [comment]
What's to test and merge?  I just pulled the diff from reddit.  All this PR does is update this repo to reflect what's live.  Also, apparently github didn't want to email me about any replies to this.

https://www.reddit.com/r/Ubuntu/wiki/config/stylesheet?v=8422e084-a1c4-11e6-b68e-0e6f55e8d3c6&v2=7d4c9cc0-20b6-11e7-8fe4-0e5c99692b94

**Comment by dakira** [comment]
@aperson that's strange.. anyway.. I'll merge this.. I just didn't want to interfere with @Daniel-McGuire because he's handling all the CSS stuff.

**Comment by Daniel-McGuire** [comment]
I never got an email for any of this.

Nothing is to be done now yes? Sorry for not seeing this.

**Comment by aperson** [comment]
All is good in the hood.

**Pull request merged**
